export const TEAMS_FETCH = 'TEAMS_FETCH';
export const TEAMS_FETCH_SUCCESS = 'TEAMS_FETCH_SUCCESS';
export const TEAMS_FETCH_FAILURE = 'TEAMS_FETCH_FAILURE';

export const SEARCH_FILTER = 'SEARCH_FILTER';