export const TEAMS_FETCH = 'TEAMS_FETCH';
export const TEAMS_FETCH_SUCCESS = 'TEAMS_FETCH_SUCCESS';
export const TEAMS_FETCH_FAILURE = 'TEAMS_FETCH_FAILURE';

export const TEAM_FETCH = 'TEAM_FETCH';
export const TEAM_FETCH_SUCCESS = 'TEAM_FETCH_SUCCESS';
export const TEAM_FETCH_FAILURE = 'TEAM_FETCH_FAILURE';

export const PLAYER_FETCH =         'PLAYER_FETCH';
export const PLAYER_FETCH_SUCCESS = 'PLAYER_FETCH_SUCCESS';
export const PLAYER_FETCH_FAILURE = 'PLAYER_FETCH_FAILURE';

export const STANDINGS_FETCH = 'STANDINGS_FETCH';
export const STANDINGS_FETCH_SUCCESS = 'STANDINGS_FETCH_SUCCESS';
export const STANDINGS_FETCH_FAILURE = 'STANDINGS_FETCH_FAILURE';

export const SEARCH_FILTER = 'SEARCH_FILTER';